import moment from "moment";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "./Navbar";
import Footer from "./Footer";
import TeachersList from "./TeachersList";
import CategoryList from "./CategoryList";
import ScheduleList from "./ScheduleList";
import NavbarrTeacher from "./NavbarrTeacher";

import { DatePicker, Space, Table } from 'antd';

export default function Home() {
  const { RangePicker } = DatePicker;
  const onOk = (value) => {
    console.log('onOk: ', value);
  };
  const onChange = (value, dateString) => {
    console.log('Formatted Selected Time: ', moment(dateString[0]).format("hh:mm"));

    const n = moment(dateString[1]).format("hh") - moment(dateString[0]).format("hh");
    console.log(n)
    if (n > 1 || n < 0) {
      alert("1 tsag songono uu")
    } else {
      alert("success")
    }
  };

  const columns = [
    {
      title: 'Өдөр',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Цаг',
      dataIndex: 'age',
      key: 'age',
    },
  ];
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarrTeacher></NavbarrTeacher>
      <div className="container mx-auto">
        <Space direction="vertical" size={12}>
          {/* <DatePicker showTime onChange={onChange} onOk={onOk} /> */}
          <RangePicker
            showTime={{
              format: 'HH:00',
            }}
            format="YYYY-MM-DD HH:00"
            onChange={onChange}
            onOk={onOk}
          />
        </Space>
        <Table columns={columns} />;
        <Footer></Footer>
      </div>
    </div>
  );
}
