import moment from "moment";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "./Navbar";
import Footer from "./Footer";
import TeachersList from "./TeachersList";
import CategoryList from "./CategoryList";
import ScheduleList from "./ScheduleList";
import NavbarrTeacher from "./NavbarrTeacher";
import { useState, useEffect, useCallback } from "react";
import { DatePicker, Space, Table, Column } from 'antd';
import { PageWrapper } from "./page-warapper";
import Notification from "./Notification";
import { useRouter } from "next/router";
export default function Home() {
  const { RangePicker } = DatePicker;
  const [userrr, setUserrr] = useState("");
  const [dataa, setData] = useState([]);
  const [dataatable, setDatatable] = useState([]);
  const router = useRouter();
  const [notification, setNotification] = useState({
    message: "",
    success: false,
  });
  const array = [];
  useEffect(() => {
    setUserrr(JSON.parse(localStorage.getItem("user")));
  }, []);
  useEffect(() => {
    if (!notification.message) return;

    const timer = setTimeout(() => {
      setNotification({
        message: "",
        success: false,
      });
    }, 3000);


    return () => clearTimeout(timer);
  }, [notification]);
  const filterData = (data) => {
    const filteredData = data.filter((i) => {
      if (userrr._id) {
        return i.teacher === userrr._id;
      }
      return false;
    });

    console.log(filteredData);
    setDatatable(filteredData);
  };

  // const fetchData = async () => {
  //   const response = await fetch("http://localhost:8000/api/timetableData");
  //   const data = await response.json();
  //   console.log(data);

  //   filterData(data);
  // };
  // useEffect(() => {
  //   if (userrr) {
  //     fetchData();
  //   }
  // }, [userrr]);
  const fetchData = useCallback(async () => {
    const response = await fetch("http://localhost:8000/api/timetableData");
    const data = await response.json();
    console.log(data);

    filterData(data);
  }, [userrr]);

  useEffect(() => {
    if (userrr) {
      fetchData();
    }
  }, [userrr]);
  const onChange = async (value, dateString) => {
    console.log('Formatted Selected Time: ', moment(dateString[0]).format("YYYY-MM-DD HH:mm"), moment(dateString[1]).format("YYYY-MM-DD HH:mm"));
    const h1 = moment(dateString[0]).format("HH")
    const h2 = moment(dateString[1]).format("HH")
    const year1 = moment(dateString[0]).format("YYYY")
    const year2 = moment(dateString[1]).format("YYYY")
    const day1 = moment(dateString[0]).format("DD")
    const day2 = moment(dateString[1]).format("DD")
    const n = h2 - h1;
    console.log(h1, h2);
    if (n > 1 || n < 0 || year2 !== year1 || day2 !== day1) {
      setNotification({
        message: "Нэмэгдэж буй цагийн дээд хэмжээ 1 цаг байна.",
        success: false,
      });

    } else {
      try {
        const response = await fetch("http://localhost:8000/api/timetableData", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            sdate: moment(dateString[0]).format("YYYY-MM-DD HH:mm"),
            edate: moment(dateString[1]).format("YYYY-MM-DD HH:mm"),
            teacher: userrr._id,
          }),
        });
        const data = await response.json();
        if (data.status === "ok") {
          setNotification({
            message: "Амжилттай Нэмэгдлээ",
            success: true,
          });

        }
        console.log(data);
      } catch (error) {
        console.log(error);
      }
    }
  };
  const handleDelete = async (id) => {
    try {
      fetch(`http://localhost:8000/api/timetableDataDelete/${id}`, { method: 'DELETE' })
        .then(() => {
          setNotification({
            message: "Амжилттай устгагдлаа",
            success: true,
          });

        })
        .catch((error) => {
          console.error(error);
        });
    } catch (error) {
      console.log(error);
    }
  }

  const columns = [
    {
      title: 'Эхлэх Цаг',
      dataIndex: 'sdate',
      key: 'sdate',
    },
    {
      title: 'Дуусах Цаг',
      dataIndex: 'edate',
      key: 'edate',
    },
    {
      title: 'Action',
      key: 'action',
      render: (record) => (
        <Space size="middle">
          <button onClick={() => { handleDelete(record._id) }} className=" text-3">Delete</button>
        </Space>
      ),
    },
  ];
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarrTeacher />
      <Notification
        message={notification.message}
        success={notification.success}
      />
      <PageWrapper>
        <div className="container mx-auto">
          <Space direction="vertical" size={12}>
            {/* <DatePicker showTime onChange={onChange} onChange={onChange} /> */}
            <RangePicker
              showTime={{
                format: 'HH:00',
              }}
              format="YYYY-MM-DD HH:00"
              onChange={onChange}
            />
          </Space>
          <Table columns={columns} dataSource={dataatable}>

          </Table>
        </div>
      </PageWrapper>
      <Footer />
    </div>
  );
}
