import moment from "moment";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "./Navbar";
import Footer from "./Footer";
import TeachersList from "./TeachersList";
import CategoryList from "./CategoryList";
import ScheduleList from "./ScheduleList";
import NavbarrTeacher from "./NavbarrTeacher";

import { DatePicker, Space, Table } from 'antd';
import { PageWrapper } from "./page-warapper";

export default function Home() {
  const { RangePicker } = DatePicker;
  const onOk = (value) => {
    console.log('onOk: ', value);
  };
  const onChange = (value, dateString) => {
    console.log('Formatted Selected Time: ', moment(dateString[0]).format("hh:mm"));
    const h1 = moment(dateString[0]).format("hh")
    const h2 = moment(dateString[1]).format("hh")
    const year1 = moment(dateString[0]).format("YYYY")
    const year2 = moment(dateString[1]).format("YYYY")
    const day1 = moment(dateString[0]).format("DD")
    const day2 = moment(dateString[1]).format("DD")
    console.log(h1 + h2 + day1 + day2 + year1 + year2)
    const n = h2 - h1;
    if (n > 1 || n < 0 || year2 !== year1 || day2 !== day1) {
      alert("1 tsag songono uu")
    } else {
      alert("success")
    }
  };

  const columns = [
    {
      title: 'Өдөр',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Цаг',
      dataIndex: 'age',
      key: 'age',
    },
  ];
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarrTeacher />
      <PageWrapper>
        <div className="container mx-auto">
          <Space direction="vertical" size={12}>
            {/* <DatePicker showTime onChange={onChange} onOk={onOk} /> */}
            <RangePicker
              showTime={{
                format: 'HH:00',
              }}
              format="YYYY-MM-DD HH:00"
              onChange={onChange}
              onOk={onOk}
            />
          </Space>
          <Table columns={columns} />
        </div>
      </PageWrapper>
      <Footer />
    </div>
  );
}
