import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import TeachersList from "../components/TeachersList";
import CategoryList from "../components/CategoryList";
import ScheduleList from "../components/ScheduleList";
import Navbarr from "../components/Navbarr";
import BackButton from "../components/BackButton";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
const SubjectDetails = () => {

  const router = useRouter();
  const { subjectDetails } = router.query;
  const [dataa, setData] = useState([]);
  // const teacherlist = [];
  // teacherlist.push(JSON.parse(localStorage.getItem("FilteredTeacher")));
  // console.log(JSON.parse(localStorage.getItem("FilteredTeacher")));
  useEffect(() => {
    if (localStorage.getItem("token") === null) {
      router.push("/");
    } else {
    }
  });
  // const fetchData = async () => {
  //   return fetch("http://localhost:8000/api/teacherListBySubjects",)
  //     .then((response) => response.json())
  //     .then((data) => setData(data));
  // };
  // useEffect(() => {
  //   fetchData();
  // }, []);
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarr></Navbarr>
      <BackButton />
      <h1 className="relative xl:text-4xl text-3xl text-center text-gray-800  font-extrabold pb-6 sm:w-4/6 w-5/6 mx-auto pt-4 z-10">
        {subjectDetails}
      </h1>
      <h2 className="relative xl:text-2xl text-xl text-center text-gray-800  pb-6 sm:w-4/6 w-5/6 mx-auto pt-4 z-10">{subjectDetails}</h2>
      {JSON.parse(localStorage.getItem("FilteredTeachers")).map((i, ind) => {
        return (
          <div
            role="listitem"
            className="  xl:w-1/3 sm:w-3/4 md:w-2/5 relative mt-16 mb-32 sm:mb-24 xl:max-w-sm lg:w-2/5"
          >
            <div className="bg-50 rounded overflow-hidden shadow-md  dark:bg-gray-900">
              <div className="absolute -mt-0 w-full text-center">
                <div className="w-32 h-32 bg-indigo-100 mx-auto rounded-full shadow-2xl absolute inset-x-0 top-0 -mt-24 flex items-center justify-center text-indigo-500">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-24 w-24 z-10"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >

                    <path
                      fillRule="evenodd"
                      d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>
              </div>
              <div className=" px-6 mt-16">
                <button
                  className="mx-auto block font-bold dark:text-white text-2xl text-center mb-1"
                  key={i._id}
                  onClick={(e) => router.push(`/teacherprofile/${i._id}`)}
                >
                  {i.fname} {i.lname}
                </button>
                <p className=" text-700 text-xl text-center font-bold">
                  {i.price}₮
                </p>
                <p className="text-center text-gray-600 dark:text-gray-200 text-base pt-3 font-normal">
                  {i.tovchtaniltsuulga}
                </p>

                <div className="w-full flex justify-center pt-5 pb-5">
                  <a href="#" className="mx-5">
                    <div aria-label="Github" role="img">
                      <img
                        src="https://tuk-cdn.s3.amazonaws.com/can-uploader/gray-bg-with-description-svg1.svg"
                        alt="github"
                      />
                    </div>
                  </a>
                  <a href="#" className="mx-5">
                    <div aria-label="Twitter" role="img">
                      <img
                        src="https://tuk-cdn.s3.amazonaws.com/can-uploader/gray-bg-with-description-svg2.svg"
                        alt="twitter"
                      />
                    </div>
                  </a>
                  <a href="#" className="mx-5">
                    <div aria-label="Instagram" role="img">
                      <img
                        src="https://tuk-cdn.s3.amazonaws.com/can-uploader/gray-bg-with-description-svg3.svg"
                        alt="instagram"
                      />
                    </div>
                  </a>

                </div>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
};

export default SubjectDetails;
