import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import TeachersList from "./components/TeachersList";
import CategoryList from "./components/CategoryList";
import ScheduleList from "./components/ScheduleList";
import Navbarr from "./components/Navbarr";
export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbarr></Navbarr>
      <div className="container mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-0">
          <div className="col-span-3">
            <ScheduleList />
          </div>
          <div className="col-span-2">
            <CategoryList />
          </div>
        </div>
      </div>
      <div>
        <h1 className="xl:text-4xl text-3xl text-center text-gray-800 dark:text-white font-extrabold pb-6 sm:w-4/6 w-5/6 mx-auto pt-4">
          Recommended Teachers
        </h1>
      </div>
      <TeachersList></TeachersList>
      <Footer></Footer>
    </div>
  );
}
